/**
 * Input validation for machine registration. Pairing tokens are transferred between
 * machines by hand, which is error-prone: real failures seen in the field include
 * pasting the shell COMMAND instead of its output, and truncating the value by one
 * character when selecting it in a terminal. Both produced a bare OFFLINE badge with no
 * explanation, so we catch them at the form instead.
 */

/** Tokens generated by the install scripts: 32 random bytes, base64url, unpadded. */
export const EXPECTED_TOKEN_LENGTH = 43;

export interface FieldIssue {
  level: "error" | "warning";
  message: string;
}

/**
 * Validate a pairing token. Returns null when it looks right. Length is a WARNING, not an
 * error, because a user may legitimately supply their own token.
 */
export function validateToken(raw: string): FieldIssue | null {
  const token = raw.trim();
  if (token === "") return null; // empty is allowed (loopback agents need no token)

  if (/\s/.test(token)) {
    return {
      level: "error",
      message:
        "The token contains a space. Paste the OUTPUT of the command, not the command itself.",
    };
  }
  if (token.startsWith("cat ") || token.includes("/") || token.includes("~")) {
    return {
      level: "error",
      message:
        "That looks like a file path or command. Run it on the monitored machine and paste what it prints.",
    };
  }
  if (!/^[A-Za-z0-9._~-]+$/.test(token)) {
    return {
      level: "error",
      message: "The token contains characters a generated token never has.",
    };
  }
  if (token.length !== EXPECTED_TOKEN_LENGTH) {
    return {
      level: "warning",
      message: `Tokens from the install scripts are ${EXPECTED_TOKEN_LENGTH} characters; this is ${token.length}. If you copied it by hand, check for a missing character.`,
    };
  }
  return null;
}

/** Validate a `host:port` (or full URL) address. */
export function validateAddress(raw: string): FieldIssue | null {
  const addr = raw.trim();
  if (addr === "") return { level: "error", message: "Address is required." };
  if (/\s/.test(addr))
    return { level: "error", message: "Address must not contain spaces." };

  const withoutScheme = addr.replace(/^https?:\/\//i, "");
  const host = withoutScheme.split("/")[0] ?? "";
  if (!host.includes(":")) {
    return {
      level: "warning",
      message:
        "No port given - the agent listens on 47600, e.g. my-machine.local:47600.",
    };
  }
  const port = Number(host.split(":").pop());
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    return {
      level: "error",
      message: "Port must be a number between 1 and 65535.",
    };
  }
  return null;
}
